### ISSUE TITLE
[bug] asset can not load from relative path

### ISSUE THREAD

**Issue by ghanbari** [helios-ag/FMElfinderBundle#142]
my project is in subdirectory of web root, `/var/www/test/a/symfony_root_project/web`

when i open `http://localhost/test/a/symfony_root_project/web/elfinder`, i see that bundle try load asset from `/assets/jquery/jquery.js` and no from `/test/a/symfony_root_project/web/assets/jquery/jquery.js`

**Comment by gittix09** [comment]
Hello!! I had the same problem... Elfinder was not loading at all and there were a lot of  '404 Cannot load resource...' in the browser console. 
I solved the problem creating a "domain" that points to the symfony_root_project/web directory.

For example "mysite.localhost". So, the link given to elfinder would be http://mysite.localhost/app_dev.php/elfinder  (dev environment)
or 
http://mysite.localhost/elfinder (prod environment)

Hope this helps

**Comment by wadjeroudi** [comment]
You need to set the variable "assets_path" in your elfinder config:

fm_elfinder:
    assets_path: '/subfolder/assets'
    instances:
        default:
...etc

**Comment by xserrat** [comment]
Hi, 

I am using this bundle in order to load images from a server but I have the same problems when I try to load assets. Are there some config to set the correct route without setting manually with 'assets_path' key?

Thanks.

**Comment by helios-ag** [comment]
The default behaviour for bundle is a project with configured vhost, and configured composer.json with following settings:
```json
{
    "config": {
        "component-dir": "web/assets"
    }
}
```
So assets placed under web/assets folder. But if you move assets somewhere else manually, you should set assets_path.

**Comment by xserrat** [comment]
Thank you @helios-ag for your clarification but I haven't moved my assets. The only thing is that my configured vhost has an alias in order to define symfony project as a specific path as you can see at bottom: 

*www.example.com/<name-project>/*

This configuration is used in order to have routes in a different symfony projects because of each one will be placed at different web server. So in this case, I don't know if it would be possible that bundle getting the symfony root path to define where is the "/" page and knowing the assets path.

**Comment by helios-ag** [comment]
Well,  in this case, do you have elfinder assets under vendor dir? The 'component' should copy them from vendor dir to web/assets directory, according to component - dir option.

**Comment by xserrat** [comment]
Yes, I have elfinder assets directory defined as you said previously. The possible solution could be to change component-dir value through command-line (because depending on the environment I need a value or another one). However, this solution causes the ```composer update``` command usage because of composer use the new config value on execute, and the good solution would be using the ```composer install``` command in order to use the same composer library versions in ```dev``` and ```prod``` environments.

Thanks for your responses.

**Comment by helios-ag** [comment]
There is also option to use version 4 of the bundle, which contains assets 'internally'.

**Comment by xserrat** [comment]
Perfect, currently I was using version 5.1.

**Comment by sunviwo** [comment]
@gittix09 can't find any "domain" option in this bundle's configs.
